export enum Icon {
  bell = 'bell',
  briefcase = 'briefcase',
  calendar = 'calendar',
  check = 'check',
  close = 'close',
  cog = 'cog',
  collection = 'collection',
  documents = 'documents',
  dots = 'dots',
  down = 'down',
  download = 'download',
  home = 'home',
  left = 'left',
  loading = 'loading',
  office = 'office',
  plus = 'plus',
  right = 'right',
  user = 'user',
  users = 'users',
}
