export enum Icon {
  bell = 'bell',
  briefcase = 'briefcase',
  calendar = 'calendar',
  check = 'check',
  cog = 'cog',
  collection = 'collection',
  documents = 'documents',
  dots = 'dots',
  down = 'down',
  home = 'home',
  office = 'office',
  plus = 'plus',
  user = 'user',
  users = 'users',
}
